# Generated by Django 5.0 on 2026-02-28 00:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_window_start", models.TimeField(help_text="Daily session window start time")),
                ("session_window_end", models.TimeField(help_text="Daily session window end time")),
                ("shorts_limit", models.PositiveIntegerField(default=10)),
                ("min_duration_seconds", models.PositiveIntegerField(default=60)),
                (
                    "sessions_per_day_min",
                    models.PositiveIntegerField(
                        default=2,
                        validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(3)],
                    ),
                ),
                (
                    "sessions_per_day_max",
                    models.PositiveIntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(3)],
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("imitate", "Imitate"), ("optimize", "Optimize")],
                        default="imitate",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="InterestProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category_weights", models.JSONField(blank=True, default=dict)),
                ("topic_weights", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("planned_start", models.DateTimeField()),
                ("planned_end", models.DateTimeField()),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("imitate", "Imitate"), ("optimize", "Optimize")],
                        default="imitate",
                        max_length=16,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="YouTubeTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("query", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="VideoDecision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("video_id", models.CharField(max_length=64)),
                ("video_url", models.URLField()),
                ("title", models.CharField(max_length=300)),
                ("duration_seconds", models.PositiveIntegerField()),
                ("action", models.CharField(choices=[("watch", "Watch"), ("skip", "Skip")], max_length=8)),
                ("reason", models.TextField(blank=True)),
                ("watched_seconds", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="video_decisions", to="agent.session"),
                ),
            ],
        ),
    ]
